Repository analogdevicesinc/testbenches, pull requests merged in 2024-04, with the labels that each got.

#88 fmcomms2: Updated version register check
  fmcomms2/tests/test_program.sv
Labels: bug

#87 regmap: Added get reset value and update functions
  common/sv/adi_regmap_adc_pkg.sv
  common/sv/adi_regmap_axi_ad7616_pkg.sv
  common/sv/adi_regmap_clkgen_pkg.sv
  common/sv/adi_regmap_clock_monitor_pkg.sv
  common/sv/adi_regmap_common_pkg.sv
  common/sv/adi_regmap_dac_pkg.sv
  common/sv/adi_regmap_dmac_pkg.sv
  common/sv/adi_regmap_fan_control_pkg.sv
  common/sv/adi_regmap_gpreg_pkg.sv
  common/sv/adi_regmap_hdmi_pkg.sv
  common/sv/adi_regmap_iodelay_pkg.sv
  common/sv/adi_regmap_jesd_rx_pkg.sv
  common/sv/adi_regmap_jesd_tpl_pkg.sv
  common/sv/adi_regmap_jesd_tx_pkg.sv
  common/sv/adi_regmap_pwm_gen_pkg.sv
  common/sv/adi_regmap_spi_engine_pkg.sv
  common/sv/adi_regmap_system_id_pkg.sv
  common/sv/adi_regmap_tdd_gen_pkg.sv
  common/sv/adi_regmap_tdd_trans_pkg.sv
  common/sv/adi_regmap_xcvr_pkg.sv
Labels: enhancement

#94 regmap: Updated functions and register namings
  ad463x/tests/test_program.sv
  ad7606x/tests/test_program.sv
  ad7616/tests/test_program_pi.sv
  ad7616/tests/test_program_si.sv
  adrv9001/tests/test_program.sv
  common/sv/adi_regmap_pwm_gen_pkg.sv
  common/sv/adi_regmap_xcvr_pkg.sv
  fmcomms2/tests/test_program.sv
  pulsar_adc_pmdz/tests/test_program.sv
  pulsar_adc_pmdz/tests/test_sleep_delay.sv
  spi_engine/tests/test_program.sv
  spi_engine/tests/test_sleep_delay.sv
Labels: bug

#91 Watchdog
  axis_sequencers/Makefile
  axis_sequencers/cfgs/cfg1.tcl
  axis_sequencers/system_project.tcl
  axis_sequencers/tests/test_program.sv
  common/sv/watchdog.sv
Labels: enhancement

#66 i3c_controller: Add testbench project
  common/sv/adi_regmap_i3c_controller_pkg.sv
  i3c_controller/Makefile
  i3c_controller/README.md
  i3c_controller/cfgs/cfg1.tcl
  i3c_controller/system_bd.tcl
  i3c_controller/system_project.tcl
  i3c_controller/system_tb.sv
  i3c_controller/tests/test_program.sv
  i3c_controller/waves/cfg1.wcfg
Labels: new

#76 script_update: Write parameters into parameters.log where the project is created
  axi_tdd/cfgs/cfg1.tcl
  axi_tdd/system_bd.tcl
  dma_loopback/cfgs/cfg1.tcl
  dma_loopback/system_bd.tcl
  scripts/adi_sim.tcl
Labels: enhancement

#96 fmcomms2: Fix test program, missing end
  fmcomms2/tests/test_program.sv
Labels: bug

#63 Scoreboard
  common/sv/mailbox.sv
  common/sv/scoreboard.sv
  common/sv/x_monitor.sv
  scoreboard/Makefile
  scoreboard/README.md
  scoreboard/cfgs/cfg1.tcl
  scoreboard/environment.sv
  scoreboard/system_bd.tcl
  scoreboard/system_project.tcl
  scoreboard/system_tb.sv
  scoreboard/tests/test_program.sv
  scoreboard/waves/cfg1.wcfg
Labels: enhancement, new

#98 scripts: fixup cygwin, use sh as subshell
  scripts/project-sim.mk
Labels: bug
