Repository analogdevicesinc/testbenches, pull requests merged in 2024-02, with the labels that each got.

#60 data_offload: Add missing library dependency
  data_offload/Makefile
  data_offload_2/Makefile
Labels: bug

#56 scripts: No config rebuild
  scripts/project-sim.mk
Labels: enhancement

#58 ad7616: Update tb
  ad7616/cfgs/cfg_pi.tcl
  ad7616/cfgs/cfg_si.tcl
  ad7616/system_bd.tcl
  ad7616/system_project.tcl
  ad7616/system_tb.sv
  ad7616/tests/test_program_pi.sv
  ad7616/tests/test_program_si.sv
  ad7616/waves/cfg_pi.wcfg
  ad7616/waves/cfg_si.wcfg
Labels: update

#62 dmac: Update
  ad463x/Makefile
  ad463x/system_project.tcl
  ad7606x/Makefile
  ad7606x/system_project.tcl
  ad7616/Makefile
  ad7616/system_project.tcl
  ad9083/Makefile
  ad9083/system_project.tcl
  ad_quadmxfe1_ebz/Makefile
  ad_quadmxfe1_ebz/system_project.tcl
  adrv9001/Makefile
  adrv9001/system_project.tcl
  adrv9009/Makefile
  adrv9009/system_project.tcl
  common/sv/adi_peripheral_pkg.sv
  common/sv/adi_regmap_adc_pkg.sv
  common/sv/adi_regmap_dmac_pkg.sv
  common/sv/adi_regmap_pkg.sv
  common/sv/axi_dmac_pkg.sv
  common/sv/dma_trans.sv
  common/sv/dmac_api.sv
  dma_loopback/Makefile
  dma_loopback/system_project.tcl
  fmcomms2/Makefile
  fmcomms2/system_project.tcl
  hbm/Makefile
  hbm/system_project.tcl
  jesd_loopback/Makefile
  jesd_loopback/system_project.tcl
  jesd_loopback_64b/Makefile
  jesd_loopback_64b/system_project.tcl
  mxfe/Makefile
  mxfe/system_project.tcl
  pulsar_adc_pmdz/Makefile
  pulsar_adc_pmdz/system_project.tcl
Labels: update

#71 ad7616: Rename irq port
  ad7616/system_bd.tcl
  ad7616/system_tb.sv
  ad7616/tests/test_program_si.sv
Labels: update

#72 data_offload: Fixed axi_write calls
  common/sv/data_offload_api.sv
Labels: bug

#61 test_harness: Update
  ad463x/tests/test_program.sv
  ad7606x/tests/test_program.sv
  ad7616/tests/test_program_pi.sv
  ad7616/tests/test_program_si.sv
  ad9083/system_bd.tcl
  ad_quadmxfe1_ebz/tests/test_dma.sv
  ad_quadmxfe1_ebz/tests/test_program.sv
  ad_quadmxfe1_ebz/tests/test_program_64b66b.sv
  adrv9001/tests/test_program.sv
  adrv9009/tests/test_program.sv
  axi_tdd/tests/test_program.sv
  common/sv/test_harness_env.sv
  common/test_harness/test_harness_system_bd.tcl
  dma_loopback/tests/test_program.sv
  fmcomms2/tests/test_program.sv
  hbm/tests/test_program.sv
  jesd_loopback/tests/test_program.sv
  jesd_loopback_64b/tests/test_program.sv
  mxfe/tests/test_program.sv
  pulsar_adc_pmdz/tests/test_program.sv
  pulsar_adc_pmdz/tests/test_sleep_delay.sv
  scripts/adi_sim.tcl
Labels: update
