Repository analogdevicesinc/testbenches, pull requests merged in 2024-11, with the labels that each got.

#132 docs: Add ad463x doc support
  docs/testbenches/project_based/ad463x/ad463x_tb.svg
  docs/testbenches/project_based/ad463x/index.rst
  docs/testbenches/project_based/index.rst
Labels: documentation

#134 ad7616: Updated FPGA part number
  testbenches/project/ad7616/system_project.tcl
Labels: bug

#133 Add ad738x doc
  docs/testbenches/project_based/ad738x/ad738x_tb.svg
  docs/testbenches/project_based/ad738x/index.rst
  docs/testbenches/project_based/index.rst
Labels: documentation

#135 Doc watchdog
  docs/library/drivers/common/index.rst
  docs/library/drivers/common/watchdog/index.rst
Labels: documentation

#136 Doc test harness
  docs/library/utilities/index.rst
  docs/library/utilities/test_harness/index.rst
Labels: documentation

#140 README.md: header update
  README.md
Labels: documentation

#141 docs: Add ad7606 doc
  docs/testbenches/project_based/ad7606/ad7606x_tb.svg
  docs/testbenches/project_based/ad7606/index.rst
  docs/testbenches/project_based/index.rst
Labels: documentation

#143 spi_engine_regmap: Updated version
  library/regmaps/adi_regmap_spi_engine_pkg.sv
Labels: bug

#145 doc: Added section on how to open testbench in GUI
  docs/user_guide/build_tb.rst
Labels: documentation

#147 docs: Add Base testbench page
  docs/testbenches/ip_based/base/base_tb.svg
  docs/testbenches/ip_based/base/index.rst
  docs/testbenches/ip_based/index.rst
  testbenches/ip/base/tests/test_program.sv
Labels: documentation

#148 Doc axis sequencers
  docs/testbenches/ip_based/axis_sequencers/axis_sequencers_tb.svg
  docs/testbenches/ip_based/axis_sequencers/index.rst
  docs/testbenches/ip_based/index.rst
Labels: documentation

#150 Doc common deps
  docs/testbenches/common/dependency_common.rst
  docs/testbenches/ip_based/axis_sequencers/index.rst
  docs/testbenches/ip_based/base/index.rst
  docs/testbenches/ip_based/util_pack/index.rst
  docs/testbenches/project_based/ad463x/index.rst
  docs/testbenches/project_based/ad738x/index.rst
  docs/testbenches/project_based/ad7606/index.rst
  docs/testbenches/project_based/pulsar_adc/index.rst
  docs/testbenches/project_based/template/index.rst
Labels: documentation

#146 templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: enhancement
