Repository analogdevicesinc/testbenches, pull requests merged in 2024-08, with the labels that each got.

#116 spi_engine: Updated sanity tests for affected projects
  ad463x/tests/test_program.sv
  ad738x/tests/test_program.sv
  ad7616/tests/test_program_si.sv
  pulsar_adc_pmdz/tests/test_program.sv
  pulsar_adc_pmdz/tests/test_sleep_delay.sv
Labels: update

#112 SPI Engine: improve instruction macros
  common/sv/spi_engine_instr_pkg.sv
  spi_engine/tests/test_program.sv
  spi_engine/tests/test_sleep_delay.sv
Labels: update

#97 Util pack
  common/sv/scoreboard.sv
  common/sv/scoreboard_pack.sv
  util_pack/Makefile
  util_pack/README.md
  util_pack/cfgs/cfg1.tcl
  util_pack/cfgs/cfg_rand.tcl
  util_pack/environment.sv
  util_pack/system_bd.tcl
  util_pack/system_project.tcl
  util_pack/system_tb.sv
  util_pack/tests/test_program.sv
  util_pack/waves/cfg1.wcfg
  util_pack/waves/cfg_rand.wcfg
Labels: new

#109 m_axis_sequencer: Update
  common/sv/m_axis_sequencer.sv
Labels: bug, update

#119 SPI Engine: update sleep delay time
  common/sv/spi_engine_instr_pkg.sv
  pulsar_adc_pmdz/tests/test_sleep_delay.sv
  spi_engine/tests/test_sleep_delay.sv
Labels: bug
